trigger: none
pr: none

variables:
- group: Pipeline
- group: Management

stages:
# Management Resource
- stage: DeployManagementResource
  displayName: Deploy Management Resources
  jobs:
    - job: TerraformStateStorage
      displayName: Terraform State Storage
      pool:
        poolImage: $(pipeline#vmImage)
      workspace:
        clean: all
      steps:
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: Deploying
        inputs:
          deploymentScope: Subscription
          connectedServiceName: $(management#state.azure.connection)
          subscriptionId: $(management#state.azure.subscription)
          location: $(management#state.azure.location)
          csmFile: ./arm/azuredeploy.json
          csmParametersFile: ./arm/azuredeploy.parameters.json
