variables:
- group: Pipeline
- group: Management 

stages:
# Management Resource
- stage: ManagementResource
  displayName: Deploy Management Resources
  jobs:
    - job: TerraformStateStorageBuild
      displayName: Build Terraform State Storage
      pool:
        poolImage: ${{ variables['pipeline#vmImage'] }}
      workspace:
        clean: all
      steps:
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: Deploying
        inputs:
          deploymentScope: Subscription
          ConnectedServiceName: Azure
          #azureResourceManagerConnection: Azure #${{ variables['management#state.azure.connection'] }}
          subscriptionId: '180ecb74-b1c1-4333-afa1-9b42bbc049ac' # ${{ variables['management#state.azure.subscription'] }}
          location: eastus2 # ${{ variables['management#state.azure.location'] }}
          csmFile: ./arm/azuredeploy.json
          csmParametersFile: ./arm/azuredeploy.parameters.json
